services:
  - postgres:latest

variables:
  POSTGRES_DB: securella-api_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

stages:
  - test

.test: &test
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  except:
    - triggers

rspec:
  <<: *test
  script:
    - bundle exec rake db:test:prepare
    - bundle exec rspec

linter:
  <<: *test
  script:
    - bundle exec rubocop
