default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: securella-api_development

test:
  <<: *default
  host: postgres
  database: securella-api_test


production:
  <<: *default
  adapter: postgresql
  host: localhost
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
